const COLORS = {
    DARK_COLOR: '#000',
    LIGHT_DARK_COLOR: '#6D6D6D',
    BACKGROUND_COLOR: '#f5f5f5',
    LIGHT_GREY_COLOR: '#EEE',
    WHITE_COLOR: '#FFF',
    INPUT_BORDER_COLOR: '#EEE',
    DARK_COLOR: '#000',
    LIGHT_DARK_COLOR: '#6D6D6D',
    BACKGROUND_COLOR: '#FAFAFA',
    THEME_COLOR: '#008ED5',
    BLUE_COLOR: '#008ED5',
    GREEN_COLOR: '#3DB466',
    ORANGE_COLOR: '#FFBB00',
    DARK_GREEN_COLOR: '#20CABE',
    LIGHT_GREY_COLOR: '#DDD',
    ERROR_COLOR: '#FA5151',
    SUCCESS_COLOR: '#8BC34A',
}



export { COLORS };